### ISSUE TITLE
organism: RecentCarwashSlider 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_USER#27]
홈화면 콘텐츠 중 가장 하단에 위치한 최근 이용 내역 슬라이더

## Tasks
- [x] RecentCarwashItem 컴포넌트를 아이템 개수만큼 Array.map()으로 표현
- [x] 가로 스크롤바 제거
- [x] tailwind 스타일 추가
