### ISSUE TITLE
atom: GNB 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_USER#4]
## Description
앱 전역적으로 화면 하단에 표시되는 네비게이션 바

## Tasks
- [x] 각 메뉴 아이콘 삽입
- [x] 각 메뉴 라벨 삽입
- [x] 선택된 메뉴는 파란색으로 표시

## Reference
https://velog.io/@gym/React-React%EB%A1%9C-%ED%95%98%EB%8B%A8%ED%83%AD-%EB%A7%8C%EB%93%A4%EA%B8%B0

**Comment by juyeongnoh** [comment]
## Todo
- [ ] 사용자가 메뉴를 더 잘 선택할 수 있게 각 GNB 아이템의 터치 영역 늘리기

**Comment by juyeongnoh** [comment]
컴포넌트 구현 완료
