### ISSUE TITLE
MSW mock data 구현

### ISSUE THREAD

**Issue by catnofat** [Step3-kakao-tech-campus/Team10_FE_USER#63]
## Tasks
- [ ] carwashes_nearby (GET)
- [ ] carwashes_search (GET)
- [ ] carwashes_introduction(GET)
- [ ] carwashes_reviews(GET)
- [ ] reviews(GET)
- [ ] carwashes_bays(GET)
- [ ] reservations(GET)
- [ ] reservation_currentstatus(GET)
- [ ] reservation_recent(GET)
- [ ] reviews(POST)
- [ ] carwashes_reservations(POST)

## References
- [sample](https://www.google.com/)
