### ISSUE TITLE
molecule: CarwashCard 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_USER#8]
## Description
홈화면 "이런 세차장 어때요?" 항목에 표시되는 세차장 정보

## Tasks
- [x] Photo 컴포넌트 활용하여 사진 표시
- [x] 별점은 Star 컴포넌트 활용
- [x] 거리는 DistanceFromHere 컴포넌트 활용
